import "./globals.css";
import { Barlow } from "next/font/google";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Project Stack",
  description: "Generated by create next app",
  icons: [
    { rel: "icon", url: "/favi.ico", sizes: "16x16" },
    { rel: "icon", url: "/favicon-32x32.png", sizes: "32x32" },
    { rel: "apple-touch-icon", url: "/apple-touch-icon.png", sizes: "180x180" },
    { rel: "icon-512", url: "/android-chrome-512x512.png", sizes:"512x512"}
  ],

};

const barlow = Barlow({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
  variable: "--font-barlow",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${barlow.className} font-[var(--font-barlow)] antialiased`}>
        {children}
      </body>
    </html>
  );
}
