import type { Metadata } from "next";
import "./globals.css";
import { Barlow } from "next/font/google";
import Footer from '../components/Footer';
import Navbar from "@/components/Navbar";


const barlow = Barlow({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  display: 'swap',
  variable: '--font-barlow', 
});


export const metadata: Metadata = {
  title: "Project Stack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlow.className} font-[var(--font-barlow)] antialiased`}
      >
          <Navbar/>
          {children}
          <Footer/>
      </body>
    </html>
  );
}
