"use client";
import type { Metadata } from "next";
import "./globals.css";
import { Barlow } from "next/font/google";
import Footer from '../components/Footer';
import Navbar from "@/components/Navbar";
import AuthProvider from "../../context/AuthProvider";
import { usePathname } from "next/navigation";

const barlow = Barlow({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  display: 'swap',
  variable: '--font-barlow', 
});


const metadata: Metadata = {
  title: "Project Stack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const hideLayout = ["/sign-in","/onboarding"].includes(pathname);

  return (
    <html lang="en">
      <body
        className={`${barlow.className} font-[var(--font-barlow)] antialiased`}
      >
        <AuthProvider>
          {!hideLayout && <Navbar/>}
            {children}
          {!hideLayout && <Footer/>}
        </AuthProvider>
      </body>
    </html>
  );
}
